services:
  frontend:
    container_name: twinpin-client
    build: .
    ports:
      - "5173:5173"
    networks:
      - twinpin-network
    env_file:
      - ../.env
    restart: unless-stopped

networks:
  twinpin-network:
    external: true